export type {
  ComponentCapability,
  ComponentCategory,
  ComponentDefinition,
  ComponentDefinitionInput,
  ComponentDefinitionSnapshot,
  ComponentHydrationResult,
  ComponentDiagnosticSeverity,
  ComponentKey,
  ComponentPersistenceEntry,
  ComponentPersistenceOperation,
  ComponentPersistenceResult,
  ComponentPersistenceSnapshot,
  ComponentPersistenceStatus,
  ComponentPersistenceSummary,
  ComponentPropDefinition,
  ComponentPropsSchema,
  ComponentPropType,
  ComponentRegistrationOptions,
  ComponentRegistryDiagnosticEntry,
  ComponentRegistryError,
  ComponentRegistrySnapshot,
  ComponentRegistryStatus,
  ComponentRegistryWarning,
  ComponentResolutionResult,
  ComponentSlotDefinition,
  ComponentType,
  ComponentValidationResult,
  IComponentRegistry,
  IComponentPersistenceService,
  IComponentResolver,
  IComponentSnapshotService,
  IComponentValidator,
  HydrateComponentRegistryInput,
  ListPersistedComponentsInput,
  LoadComponentInput,
  PersistAllComponentsInput,
  PersistComponentInput
} from "./components.js";
export type {
  CompositionActionBinding,
  CompositionSnapshotEntry,
  CompositionSnapshotEntrySummary,
  CompositionSnapshotPurpose,
  CompositionBinding,
  CompositionDiagnosticEntry,
  CompositionDiagnosticSeverity,
  CompositionError,
  CompositionInput,
  CompositionNode,
  CompositionResolutionResult,
  CompositionSourceType,
  CompositionStatus,
  CompositionTree,
  CompositionValidationResult,
  CompositionVisibilityRule,
  CompositionWarning,
  ICompositionResolver,
  ICompositionSnapshotService,
  ICompositionValidator,
  IUICompositionRuntime,
  IUICompositionPersistenceService,
  UICompositionSnapshot,
  UICompositionPersistenceOperation,
  UICompositionPersistenceResult,
  UICompositionPersistenceSnapshot,
  UICompositionPersistenceStatus,
  UICompositionPersistenceSummary,
  ComposeAndPersistInput,
  DeleteCompositionSnapshotInput,
  ListCompositionSnapshotsInput,
  LoadCompositionSnapshotInput,
  LoadLatestCompositionSnapshotInput,
  PersistCompositionSnapshotInput
  , SnapshotRetentionStatus
  , SnapshotAuditOperation
  , SnapshotAuditResultStatus
  , SnapshotRetentionScope
  , SnapshotRetentionPolicy
  , SnapshotAuditEntry
  , SnapshotRetentionRunSummary
  , SnapshotRetentionAuditSummary
  , SnapshotRetentionAuditSnapshot
  , SnapshotChecksumResult
  , SnapshotChecksumVerificationResult
  , SnapshotLatestRepairResult
  , SnapshotRetentionResult
  , RecordSnapshotAuditEntryInput
  , ListSnapshotAuditEntriesInput
  , ComputeSnapshotChecksumInput
  , VerifySnapshotChecksumInput
  , EnforceSnapshotRetentionForSourceInput
  , EnforceSnapshotRetentionInput
  , RepairLatestPointerInput
  , ISnapshotRetentionAuditService
} from "./ui-composition.js";
export type {
  IConfigurationProvider,
  ConfigurationQuery,
  ConfigurationScope
} from "./configuration.js";
export type {
  CorrelationContext,
  ExecutionContextInput,
  ExecutionContextSnapshot,
  ExecutionContextValidationIssue,
  ExecutionContextValidationResult,
  IExecutionContext,
  IExecutionContextFactory,
  IExecutionContextValidator,
  IRequestContext,
  ITenantContext,
  IUserContext,
  IWorkspaceContext,
  LocaleContext,
  RequestContext,
  TenantContext,
  TenantStatus,
  UserContext,
  WorkspaceContext
} from "./context.js";
export { CONFIGURATION_KEYS } from "./configuration.js";
export type {
  ConfigurationDiagnosticEntry,
  ConfigurationHydrationResult,
  ConfigurationDiagnosticSeverity,
  ConfigurationError,
  ConfigurationKey,
  ConfigurationPersistenceEntry,
  ConfigurationPersistenceOperation,
  ConfigurationPersistenceResult,
  ConfigurationPersistenceSnapshot,
  ConfigurationPersistenceStatus,
  ConfigurationPersistenceSummary,
  ConfigurationPersistenceValue,
  ConfigurationResolutionResult,
  ConfigurationSnapshot,
  ConfigurationSourceSnapshot,
  ConfigurationSourceType,
  ConfigurationValidationIssue,
  ConfigurationValidationResult,
  ConfigurationValue,
  ConfigurationValues,
  ConfigurationWarning,
  IConfigurationResolver,
  IConfigurationPersistenceService,
  IConfigurationSource,
  IConfigurationValidator,
  RuntimeMode,
  VeltryxEnvironment,
  HydrateConfigurationInput,
  ListConfigurationKeysInput,
  LoadConfigurationKeyInput,
  PersistConfigurationInput,
  PersistConfigurationKeyInput
} from "./configuration.js";
export type {
  EventDispatchError,
  EventDispatchResult,
  EventEnvelope,
  EventHandler,
  EventHandlerResult,
  EventMetadata,
  EventPublishInput,
  EventRegistration,
  EventSubscription,
  EventSubscriptionInput,
  EventType,
  IEventBus,
  IEventDispatcher,
  IEventPublisher,
  LegacyEventEnvelope
} from "./events.js";
export type {
  IKernelStatusService,
  KernelBootStatus,
  KernelDiagnosticEntry,
  KernelDiagnosticSeverity,
  KernelModuleSystemStatus,
  KernelRegistryStatus,
  KernelSnapshotAvailability,
  KernelStatus,
  KernelStatusMetric,
  KernelStatusSnapshot
} from "./kernel-status.js";
export type {
  IMetadataEngine,
  HydrateMetadataRegistryInput,
  IMetadataPersistenceService,
  IMetadataRegistry,
  IMetadataResolver,
  IMetadataSnapshotService,
  IMetadataValidator,
  MetadataAction,
  MetadataActionType,
  MetadataDiagnosticEntry,
  MetadataEngineSnapshot,
  MetadataEngineStatus,
  MetadataEntity,
  MetadataError,
  MetadataField,
  MetadataFieldOption,
  MetadataFieldType,
  MetadataFilterDefinition,
  MetadataForm,
  MetadataFormField,
  MetadataLayoutDefinition,
  MetadataList,
  MetadataListColumn,
  MetadataMenu,
  MetadataMenuItem,
  MetadataPersistenceOperation,
  MetadataPersistenceResult,
  MetadataPersistenceSnapshot,
  MetadataPersistenceStatus,
  MetadataPersistenceSummary,
  MetadataHydrationResult,
  MetadataNamespace,
  MetadataNamespaceSnapshot,
  MetadataPage,
  MetadataPageSection,
  MetadataPermissionDeclaration,
  MetadataQuery,
  MetadataRecord,
  MetadataRegistrationOptions,
  MetadataRelation,
  MetadataRelationType,
  MetadataResolutionResult,
  MetadataResource,
  MetadataResourceSnapshot,
  MetadataResourceType,
  MetadataSortDefinition,
  MetadataStatus,
  MetadataValidationResult,
  MetadataValidationRule,
  MetadataView,
  MetadataViewType,
  MetadataWarning,
  ListMetadataResourcesInput,
  LoadMetadataResourceInput,
  PersistMetadataNamespaceInput,
  PersistMetadataResourceInput
} from "./metadata.js";
export type {
  IModuleCatalog,
  IModuleDiscovery,
  IModuleCycleDetector,
  IModuleDependencyGraph,
  IModuleDependencyResolver,
  IModuleDiscoveryValidator,
  IModuleLoader,
  IModuleLoadingService,
  IModuleRegistry,
  IModuleStateValidator,
  IModuleManifest,
  IModuleManifestParser,
  IModuleManifestValidator,
  ModuleCompatibility,
  ModuleDependency,
  ModuleDependencyConflictEntry,
  ModuleDependencyCycle,
  ModuleDependencyEdge,
  ModuleDependencyMissingEntry,
  ModuleDependencyResolution,
  ModuleDependencyResolutionReport,
  ModuleDependencyResolutionResult,
  ModuleDescriptor,
  IModuleTopologicalSorter,
  ModuleDiscoveryDuplicateEntry,
  ModuleDiscoveryIgnoredEntry,
  ModuleDiscoveryInvalidEntry,
  ModuleDiscoveryReport,
  ModuleDiscoveryResult,
  ModuleDiscoveryValidationResult,
  ModuleLifecycleState,
  ModuleLoadingIgnoredEntry,
  ModuleLoadingRejectedEntry,
  ModuleLoadingReport,
  ModuleLoadingResult,
  ModuleLoadingState,
  ModuleManifest,
  LoadedModule,
  ModuleManifestValidationIssue,
  ModuleManifestValidationResult,
  ModuleVersion
} from "./modules.js";
export type {
  IModuleSystemStatusService,
  ModuleDependencySnapshot,
  ModuleDependencySnapshotStatus,
  ModuleDiscoveryStatus,
  ModuleLoadingStatus,
  ModulePublicSnapshot,
  ModulePublicStatus,
  ModuleResolutionStatus,
  ModuleSystemDiagnosticEntry,
  ModuleSystemDiagnosticSeverity,
  ModuleSystemError,
  ModuleSystemSnapshot,
  ModuleSystemSnapshotReports,
  ModuleSystemStatus,
  ModuleSystemWarning
} from "./module-system-status.js";
export type { IRuntime, RuntimeBootstrapResult, RuntimeSession, RuntimeState } from "./runtime.js";
export type {
  IRuntimeBootstrapService,
  RuntimeBootstrapDependencies,
  RuntimeBootstrapStatus,
  RuntimeDiagnosticEntry,
  RuntimeError,
  RuntimeLifecycleStatus,
  RuntimeStructuralBootstrapResult,
  RuntimeWarning
} from "./runtime.js";
export type {
  IRuntimeContextFactory,
  IRuntimeContextValidator,
  IRuntimeLifecycleController,
  IRuntimeStatusSnapshotService,
  RuntimeComponentRegistryContext,
  RuntimeConfigurationContext,
  RuntimeContext,
  RuntimeContextFactoryInput,
  RuntimeContextSnapshot,
  RuntimeContextValidationResult,
  RuntimeDependencyInjectionContext,
  RuntimeExecutionContextSummary,
  RuntimeModulesContext,
  RuntimeMetadataContext,
  RuntimeServicesContext,
  RuntimeUICompositionContext,
  RuntimeStatusSnapshot
} from "./runtime.js";
export { CircularDependencyError } from "./dependency-injection.js";
export type {
  DependencyInjectionDiagnosticEntry,
  DependencyInjectionError,
  DependencyInjectionSnapshot,
  DependencyInjectionStatus,
  DependencyInjectionWarning,
  IDependencyInjectionContainer,
  IProviderResolver,
  ProviderDefinition,
  ProviderDescriptorSnapshot,
  ProviderKind,
  ProviderLifecycle,
  ProviderRegistrationOptions
} from "./dependency-injection.js";
export type {
  IServiceRegistry,
  ServiceCategory,
  ServiceDescriptor,
  ServiceDescriptorInput,
  ServiceDescriptorSnapshot,
  ServiceLifecycle,
  ServiceProvider,
  ServiceRegistrationOptions,
  ServiceRegistryDiagnosticEntry,
  ServiceRegistryDiagnosticSeverity,
  ServiceRegistryError,
  ServiceRegistrySnapshot,
  ServiceRegistryStatus,
  ServiceRegistryWarning,
  ServiceScope,
  ServiceStatus,
  ServiceToken
} from "./services.js";
export type {
  CountRecordsInput,
  CreateRecordInput,
  IPersistenceProvider,
  IPersistenceService,
  IRepository,
  ListRecordsInput,
  PersistenceCollectionName,
  PersistenceDiagnostic,
  PersistenceError,
  PersistenceKey,
  PersistenceListResult,
  PersistenceNamespace,
  PersistenceOperation,
  PersistenceProviderKind,
  PersistenceProviderSnapshot,
  PersistenceRecord,
  PersistenceRecordData,
  PersistenceRecordId,
  PersistenceRecordMetadata,
  PersistenceResult,
  PersistenceSnapshot,
  PersistenceStatus,
  PersistenceSummary,
  PersistenceValue,
  PersistenceWarning,
  RepositoryInput,
  UpdateRecordInput
} from "./persistence.js";

export type {
  IStructuralEventPublisher,
  KernelBootstrapCompletedPayload,
  KernelBootstrapFailedPayload,
  KernelBootstrapStartedPayload,
  KernelReadyPayload,
  KernelStructuralEventName,
  KernelStructuralEventPayload,
  ModuleDiscoveryCompletedPayload,
  ModuleDiscoveryFailedPayload,
  ModuleDiscoveryStartedPayload,
  ModuleLoadingCompletedPayload,
  ModuleLoadingFailedPayload,
  ModuleLoadingStartedPayload,
  ModuleResolutionCompletedPayload,
  ModuleResolutionFailedPayload,
  ModuleResolutionStartedPayload,
  ModuleSystemStructuralEventName,
  ModuleSystemStructuralEventPayload,
  StructuralEventErrorPayload,
  StructuralEventName,
  StructuralEventPayload,
  StructuralEventPublishInput
} from "./structural-events.js";




