export type {
  ComponentCapability,
  ComponentCategory,
  ComponentDefinition,
  ComponentDefinitionInput,
  ComponentDefinitionSnapshot,
  ComponentKey,
  ComponentPropDefinition,
  ComponentPropsSchema,
  ComponentPropType,
  ComponentRegistrationOptions,
  ComponentRegistryDiagnosticEntry,
  ComponentRegistryError,
  ComponentRegistrySnapshot,
  ComponentRegistryStatus,
  ComponentRegistryWarning,
  ComponentResolutionResult,
  ComponentSlotDefinition,
  ComponentType,
  ComponentValidationResult,
  IComponentRegistry,
  IComponentResolver,
  IComponentSnapshotService,
  IComponentValidator
} from "@veltryx/contracts";
